# Calculate the sigmoid functions
## Libraries

In [1]:
from pandas import DataFrame, read_csv
import datetime
import math
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import pylab
from scipy.optimize import curve_fit
import os

In [2]:
working_directory ='/Users/peter/python/pyBuurtwarmte'
os.chdir(working_directory)

In [3]:
file = "EvO_Gas_Allocation_2017.csv"
EvO_gas_alloc = pd.read_csv(file, index_col=False, header=None);
EvO_gas_alloc.columns = ['Date', 'Allocation']

In [4]:
EvO_gas_alloc['Date'] = EvO_gas_alloc['Date'].apply(lambda x: pd.to_datetime(str(x), format='%d/%m/%Y'))
EvO_gas_alloc.set_index('Date', inplace=True)
EvO_gas_alloc

             Allocation
Date
2017-01-01  28683.80931
2017-01-02  29712.64248
2017-01-03  28643.28950
2017-01-04  29405.05342
2017-01-05  34851.57266
2017-01-06  40434.59331
2017-01-07  34741.39919
2017-01-08  27442.90630
2017-01-09  28132.75431
2017-01-10  24753.04912
2017-01-11  26372.10706
2017-01-12  27845.02973
2017-01-13  29509.58469
2017-01-14  31634.86991
2017-01-15  29617.75652
2017-01-16  34886.95316
2017-01-17  41473.30073
2017-01-18  39830.58099
2017-01-19  35862.24721
2017-01-20  33528.24802
2017-01-21  30993.31313
2017-01-22  33402.54676
2017-01-23  34351.43232
2017-01-24  34403.84166
2017-01-25  36388.34151
2017-01-26  36845.34311
2017-01-27  35235.39940
2017-01-28  27830.03025
2017-01-29  26713.63646
2017-01-30  28608.85239
...                 ...
2017-12-02  31725.46528
2017-12-03  29141.08788
2017-12-04  26099.32874
2017-12-05  27380.34401
2017-12-06  23440.19510
2017-12-07  32303.75374
2017-12-08  35770.37781
2017-12-09  35584.26132
2017-12-10  39526.77542
2017-12-11  29113.41497
2017-12-12  39001.59648
2017-12-13  38991.08668
2017-12-14  29857.12333
2017-12-15  36420.32152
2017-12-16  35292.95895
2017-12-17  41509.05534
2017-12-18  33944.74041
2017-12-19  33361.87117
2017-12-20  34000.29623
2017-12-21  26135.33695
2017-12-22  29743.75507
2017-12-23  27290.35955
2017-12-24  25523.36251
2017-12-25  31318.07595
2017-12-26  31228.03604
2017-12-27  33479.64388
2017-12-28  37408.87178
2017-12-29  38104.38021
2017-12-30  34529.96851
2017-12-31  25191.63287

[365 rows x 1 columns]

In [5]:
#print(df)
x_data = df['TEFF Time lag']
y_data = df['1 huishouden']
#print(x_data, y_data)

NameError: name 'df' is not defined

In [6]:
def fsigmoid(T, a, b, c, d):
     y = a / (1 + (b/(T-40)) ** c) + d
     return y

In [7]:
popt, pcov = curve_fit(fsigmoid, x_data, y_data, bounds=([ 0., -41., 0., 0],[np.inf, -35., np.inf, np.inf]))

NameError: name 'x_data' is not defined

In [8]:
print(popt)
#print(popt[0])

NameError: name 'popt' is not defined

In [9]:
x = x_data
#y = fsigmoid(x, 4.11, -39.4, 7.61, 0.169)
y = fsigmoid(x, popt[0], popt[1], popt[2], popt[3])
#print(y)
pylab.plot(x_data, 1200*y_data, 'o', label='data')
pylab.plot(x,1200*1.0*y, label='fit avg')
pylab.plot(x,1200*0.8*y, label='fit min')
pylab.plot(x,1200*1.2*y, label='fit max')
pylab.ylim(0, 15)
pylab.legend(loc='best')
pylab.show()

NameError: name 'x_data' is not defined